apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: katharine@kathar.in
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: katharine+rebble@kathar.in
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        - name: cloudflare-dns
          cloudflare:
            email: katharine@kathar.in
            apiKeySecretRef:
              name: cloudflare-api-key
              key: key
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: katharine@kathar.in
    server: https://acme-v02.api.letsencrypt.org/directory
    email: katharine+rebble@kathar.in
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cloudflare-dns
          cloudflare:
            email: katharine@kathar.in
            apiKeySecretRef:
              name: cloudflare-api-key
              key: key
